title: "MN Lite"
logo: "assets/logo.png"
copyright: 2021
author: Dave
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true
execute:
  execute_notebooks: auto
  run_in_temp: false
html:
  favicon: "assets/favicon.ico"
  use_repository_button: true
repository:
  url: https://github.com/datadavev/mnlite
  branch: main
